language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t priyam304/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true priyam304/docker-react npm run test