language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t priyam304/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true priyam304/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1" 
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-684494540934"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY 

