language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t priyam304/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true priyam304/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-923445559289"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY 
